In [4]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from urllib.parse import urlsplit, parse_qs

In [2]:
 df = pd.read_csv('./data/application_log2023_final.csv')

In [3]:
df.head()

,user_uuid,URL,timestamp,date,response_code,method,지원여부
0,5ce8f5ca-3476-4623-a60c-00c98eef3b62,@user_id,2023-12-29 13:19:50.230356 UTC,2023-12-29,200,GET,미지원
1,5ce8f5ca-3476-4623-a60c-00c98eef3b62,api/users/notifications/mark_read?id=6425064&_...,2023-12-29 13:20:17.848762 UTC,2023-12-29,200,GET,미지원
2,5ce8f5ca-3476-4623-a60c-00c98eef3b62,jobs/id/id_title,2023-12-29 13:22:22.277796 UTC,2023-12-29,200,GET,미지원
3,5ce8f5ca-3476-4623-a60c-00c98eef3b62,suggest?q=epdlxj,2023-12-29 13:21:22.99993 UTC,2023-12-29,200,GET,미지원
4,5ce8f5ca-3476-4623-a60c-00c98eef3b62,api/current_guided_action/id,2023-12-29 13:20:19.834724 UTC,2023-12-29,200,POST,미지원

In [9]:
def parse_url_components(url):
    if pd.isna(url) or not isinstance(url, str):
        return None, None
    parsed = urlsplit(url.strip())
    return parsed.path, parsed.query

def parse_query_to_dict(query):
    if pd.isna(query) or not isinstance(query, str) or not query.strip():
        return {}
    return {k: v[0] for k, v in parse_qs(query).items()}

df['Path'], df['Query'] = zip(*df['URL'].apply(parse_url_components))
df['Query_Dict'] = df['Query'].apply(parse_query_to_dict)

df.to_csv('processed_url_data.csv', index=False, encoding='utf-8-sig')

In [8]:
df

,user_uuid,URL,timestamp,date,response_code,method,지원여부,Path,Query,Query_Dict
0,5ce8f5ca-3476-4623-a60c-00c98eef3b62,@user_id,2023-12-29 13:19:50.230356 UTC,2023-12-29,200,GET,미지원,@user_id,,{}
1,5ce8f5ca-3476-4623-a60c-00c98eef3b62,api/users/notifications/mark_read?id=6425064&_...,2023-12-29 13:20:17.848762 UTC,2023-12-29,200,GET,미지원,api/users/notifications/mark_read,id=6425064&_=1703856123830,"{'id': '6425064', '_': '1703856123830'}"
2,5ce8f5ca-3476-4623-a60c-00c98eef3b62,jobs/id/id_title,2023-12-29 13:22:22.277796 UTC,2023-12-29,200,GET,미지원,jobs/id/id_title,,{}
3,5ce8f5ca-3476-4623-a60c-00c98eef3b62,suggest?q=epdlxj,2023-12-29 13:21:22.99993 UTC,2023-12-29,200,GET,미지원,suggest,q=epdlxj,{'q': 'epdlxj'}
4,5ce8f5ca-3476-4623-a60c-00c98eef3b62,api/current_guided_action/id,2023-12-29 13:20:19.834724 UTC,2023-12-29,200,POST,미지원,api/current_guided_action/id,,{}
...,...,...,...,...,...,...,...,...,...,...
7186250,167cdb14-d145-4679-b878-66a9a2d32ee9,@user_id,2023-11-14 12:12:26.780872 UTC,2023-11-14,200,GET,미지원,@user_id,,{}
7186251,167cdb14-d145-4679-b878-66a9a2d32ee9,@user_id,2023-11-14 12:11:38.859562 UTC,2023-11-14,200,GET,미지원,@user_id,,{}
7186252,f5649d90-3016-4747-9924-a05d74ee895e,api/users/id/template,2023-11-14 13:16:19.471324 UTC,2023-11-14,200,POST,미지원,api/users/id/template,,{}
7186253,f5649d90-3016-4747-9924-a05d74ee895e,verify_phone?next_url=/%40kkwangpe,2023-11-14 13:16:11.530244 UTC,2023-11-14,200,GET,미지원,verify_phone,next_url=/%40kkwangpe,{'next_url': '/@kkwangpe'}
7186254,f5649d90-3016-4747-9924-a05d74ee895e,@user_id,2023-11-14 13:16:18.579935 UTC,2023-11-14,200,GET,미지원,@user_id,,{}